// <auto-generated />
using System;
using Adagio.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Adagio.Data.Migrations
{
    [DbContext(typeof(AdagioContext))]
    [Migration("20181218120414_EntityBaseAddedToClasesAndMatricula")]
    partial class EntityBaseAddedToClasesAndMatricula
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Adagio.Data.Models.Alumno", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<DateTime>("FechaNacimiento");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("id");

                    b.ToTable("Alumno");
                });

            modelBuilder.Entity("Adagio.Data.Models.Clase", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("id");

                    b.ToTable("Clase");
                });

            modelBuilder.Entity("Adagio.Data.Models.Matricula", b =>
                {
                    b.Property<int>("AlumnoId");

                    b.Property<int>("ClaseId");

                    b.Property<int>("id");

                    b.HasKey("AlumnoId", "ClaseId");

                    b.HasIndex("ClaseId");

                    b.ToTable("Matricula");
                });

            modelBuilder.Entity("Adagio.Data.Models.Matricula", b =>
                {
                    b.HasOne("Adagio.Data.Models.Alumno", "Alumno")
                        .WithMany("Matriculas")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Adagio.Data.Models.Clase", "Clase")
                        .WithMany("Matriculas")
                        .HasForeignKey("ClaseId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
