// <auto-generated />
using System;
using AdagioApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AdagioApi.Migrations
{
    [DbContext(typeof(AdagioContext))]
    [Migration("20180801075707_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AdagioApi.Models.Alumno", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<DateTime>("FechaNacimiento");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("id");

                    b.ToTable("Alumno");
                });

            modelBuilder.Entity("AdagioApi.Models.Clase", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("id");

                    b.ToTable("Clase");
                });

            modelBuilder.Entity("AdagioApi.Models.Matricula", b =>
                {
                    b.Property<int>("idAlumno");

                    b.Property<int>("idClase");

                    b.Property<int?>("Alumnoid");

                    b.Property<int?>("Claseid");

                    b.HasKey("idAlumno", "idClase");

                    b.HasIndex("Alumnoid");

                    b.HasIndex("Claseid");

                    b.ToTable("Matricula");
                });

            modelBuilder.Entity("AdagioApi.Models.Matricula", b =>
                {
                    b.HasOne("AdagioApi.Models.Alumno", "Alumno")
                        .WithMany("Matriculas")
                        .HasForeignKey("Alumnoid");

                    b.HasOne("AdagioApi.Models.Clase", "Clase")
                        .WithMany("Matriculas")
                        .HasForeignKey("Claseid");
                });
#pragma warning restore 612, 618
        }
    }
}
